name: dotnet package

on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['8.0.x']
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
      - name: DotNetBuild
        shell: pwsh
        run: ./ci-build.ps1
      - name: Test
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Codecov
        uses: codecov/codecov-action@v3
